# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4088ec2cf193357eba0a77fd33bd8f4569a41ae1a5ebcd60a83acdc5944ea1d985b1047dab6fdd8f455be8ea6ab4504087f5110ae58b68028be4cff59ce73c4b

test:
  secret_key_base: 20005d57c2ff0882c3fcac1442151dbb5714b4e4733c10fb3283d53d8243a69cd7c131df990a4847a85b88d2b6d474b3cd20073a30835192c4778e4bf32d1d5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
